# Orb 'circleci/gcp-cli@1.8.4' resolved to 'circleci/gcp-cli@1.8.4'
version: 2
jobs:
  deploy_master:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo 'Hello deploy_master'
      - run: DATENOW=CIRCLE_CURRENT_TIME_MILLS
      - run: echo $CIRCLE_CURRENT_TIME_MILLS
      - run: echo $CIRCLE_PREVIOUS_BUILD_NUM
      - run: test -f ~/repo/data.txt && echo "data.txt exist"
  deploy_release:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run: echo 'Hello deploy_release'
      
  deploy_develop:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run: echo 'Hello deploy_develop'
workflows:
  version: 2
  workflow:
    jobs:
    #- hold: 
    #type: approval
    - deploy_master:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
    
